                                       Chapter7 Data Cleaning and Preparation

# 7.1 Handling Missing Data 

In [7]:
import pandas as pd

In [8]:
import numpy as np

In [9]:
float_data = pd.Series([1,2, np.nan, 0])

In [10]:
float_data

0    1.0
1    2.0
2    NaN
3    0.0
dtype: float64

In [11]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

## Filtering out Missing Data

In [14]:
float_data.dropna()

0    1.0
1    2.0
3    0.0
dtype: float64

In [15]:
data = pd.DataFrame([[1,2,None],[2,np.nan,3],[3,4,5]])

In [17]:
data

0    1    2
0  1  2.0  NaN
1  2  NaN  3.0
2  3  4.0  5.0

In [18]:
data.dropna()

0    1    2
2  3  4.0  5.0

In [20]:
data.dropna(how="all")

0    1    2
0  1  2.0  NaN
1  2  NaN  3.0
2  3  4.0  5.0

In [21]:
data[0]

0    1
1    2
2    3
Name: 0, dtype: int64

In [23]:
data[4] = np.nan

In [24]:
data

0    1    2   4
0  1  2.0  NaN NaN
1  2  NaN  3.0 NaN
2  3  4.0  5.0 NaN

In [25]:
data.dropna(axis="columns", how = "all")

0    1    2
0  1  2.0  NaN
1  2  NaN  3.0
2  3  4.0  5.0

In [27]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [28]:
df

0         1         2
0 -0.079759 -0.455507  0.381387
1 -1.844783  0.332224 -0.002209
2 -0.307432  0.363192  0.954376
3 -1.217154  0.521973  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

In [29]:
df.iloc[:4,1] = np.nan

In [30]:
df.loc[[0,1], 0] = np.nan

In [31]:
df

0         1         2
0       NaN       NaN  0.381387
1       NaN       NaN -0.002209
2 -0.307432       NaN  0.954376
3 -1.217154       NaN  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

In [32]:
df.dropna()

0         1         2
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

In [33]:
df.dropna(thresh=2)

0         1         2
2 -0.307432       NaN  0.954376
3 -1.217154       NaN  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

## Filling in Missing Data

In [36]:
df

0         1         2
0       NaN       NaN  0.381387
1       NaN       NaN -0.002209
2 -0.307432       NaN  0.954376
3 -1.217154       NaN  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

In [37]:
df.fillna(0)

0         1         2
0  0.000000  0.000000  0.381387
1  0.000000  0.000000 -0.002209
2 -0.307432  0.000000  0.954376
3 -1.217154  0.000000  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

In [38]:
df


0         1         2
0       NaN       NaN  0.381387
1       NaN       NaN -0.002209
2 -0.307432       NaN  0.954376
3 -1.217154       NaN  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

In [39]:
df.fillna({0:1, 1:2})

0         1         2
0  1.000000  2.000000  0.381387
1  1.000000  2.000000 -0.002209
2 -0.307432  2.000000  0.954376
3 -1.217154  2.000000  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

In [40]:
df

0         1         2
0       NaN       NaN  0.381387
1       NaN       NaN -0.002209
2 -0.307432       NaN  0.954376
3 -1.217154       NaN  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

In [41]:
df.fillna(method="ffill")

0         1         2
0       NaN       NaN  0.381387
1       NaN       NaN -0.002209
2 -0.307432       NaN  0.954376
3 -1.217154       NaN  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

In [42]:
df.fillna(data.mean())

0         1         2
0  2.000000  3.000000  0.381387
1  2.000000  3.000000 -0.002209
2 -0.307432  3.000000  0.954376
3 -1.217154  3.000000  0.879874
4 -0.590411 -1.010036 -0.741737
5  0.314956  0.014502  1.476739
6  0.378753  0.138890  1.275322

# 7.2 Data Transformation

## Removing Duplicates

In [46]:
data = pd.DataFrame({"k1":["one","two"]*3 + ["two"],
                     "k2":[1,1,2,3,3,4,4]})

In [47]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [48]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [49]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [50]:
data["v1"] = range(7)

In [51]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [53]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [54]:
data.drop_duplicates(["k1","k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## Transforming Data using a Function or Mapping

In [56]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
   ....:                               "pastrami", "corned beef", "bacon",
   ....:                               "pastrami", "honey ham", "nova lox"],
   ....:                      "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [57]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [58]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [60]:
data["animal"] = data["food"].map(meat_to_animal)

In [61]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [64]:
def get_animal(x):
    return meat_to_animal[x]

In [65]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

## Replacing Values

In [70]:
data = pd.Series([1,2,3,4,5], index = ["a","b","c","d","e"])

In [71]:
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [72]:
data.replace(1,np.nan)

a    NaN
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

In [74]:

data.replace([2,3], np.nan)

a    1.0
b    NaN
c    NaN
d    4.0
e    5.0
dtype: float64

In [76]:
data.replace([1,np.nan], [2,3])

a    2
b    2
c    3
d    4
e    5
dtype: int64

## Renaming Axis Indexes

In [80]:
data = pd.DataFrame(np.arange(12).reshape(3,4), 
index = ["ohio","colorado","new york"], 
columns=["one","two","three","four"])

In [81]:
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
new york    8    9     10    11

In [86]:
def transform(x):
    return x[:4].upper()

In [87]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [88]:
data.index = data.index.map(transform)

In [89]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [90]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [92]:
data1 = data.rename(index=str.title, columns=str.upper)

In [93]:
data1

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [94]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [97]:
data.rename(index = {"OHIO":"O"},columns={"three":3})

one  two   3  four
O       0    1   2     3
COLO    4    5   6     7
NEW     8    9  10    11

## Discretization and Binning

In [100]:
ages = [20,22,23,24,29,33,37,61,77]

In [101]:
bins = [18,25,35,60,100]

In [104]:
age_categories = pd.cut(ages,bins)

In [105]:
age_categories

[(18, 25], (18, 25], (18, 25], (18, 25], (25, 35], (25, 35], (35, 60], (60, 100], (60, 100]]
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [106]:
age_categories.value_counts()

(18, 25]     4
(25, 35]     2
(35, 60]     1
(60, 100]    2
dtype: int64

In [107]:
labels = ["youth","youngAdult","MiddleAged","Senior"]

In [109]:
age_categories =pd.cut(ages, bins, labels=labels)

In [110]:
age_categories

['youth', 'youth', 'youth', 'youth', 'youngAdult', 'youngAdult', 'MiddleAged', 'Senior', 'Senior']
Categories (4, object): ['youth' < 'youngAdult' < 'MiddleAged' < 'Senior']

In [111]:
age_categories.value_counts()

youth         4
youngAdult    2
MiddleAged    1
Senior        2
dtype: int64

In [112]:
age_categories =pd.cut(ages, 4, precision=2)

In [113]:
age_categories

[(19.94, 34.25], (19.94, 34.25], (19.94, 34.25], (19.94, 34.25], (19.94, 34.25], (19.94, 34.25], (34.25, 48.5], (48.5, 62.75], (62.75, 77.0]]
Categories (4, interval[float64, right]): [(19.94, 34.25] < (34.25, 48.5] < (48.5, 62.75] < (62.75, 77.0]]

In [114]:
age_categories.value_counts()

(19.94, 34.25]    6
(34.25, 48.5]     1
(48.5, 62.75]     1
(62.75, 77.0]     1
dtype: int64

In [115]:
age_categories =pd.qcut(ages, 4, precision=2)

In [116]:
age_categories.value_counts()

(19.99, 23.0]    3
(23.0, 29.0]     2
(29.0, 37.0]     2
(37.0, 77.0]     2
dtype: int64

In [119]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [121]:
pd.qcut(ages,[0,0.1,0.5,0.9,1.]).value_counts()

(19.999, 21.6]    1
(21.6, 29.0]      4
(29.0, 64.2]      3
(64.2, 77.0]      1
dtype: int64

In [122]:
## Detecing and filtering outliers

In [123]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))

In [124]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.059949     0.014950     0.005706    -0.012734
std       0.980320     1.015555     1.030234     0.991664
min      -3.250201    -3.378901    -2.938034    -3.842775
25%      -0.607760    -0.657363    -0.672624    -0.702897
50%       0.064670    -0.006099     0.003529    -0.017018
75%       0.708808     0.679566     0.710615     0.646900
max       2.956447     3.635538     2.848450     3.075630

In [125]:
col = data[2]

In [128]:
col

0     -0.324373
1     -0.296991
2     -0.527142
3     -0.182642
4     -0.740008
         ...   
995    0.353708
996   -0.607005
997    0.248929
998    0.390987
999   -1.319623
Name: 2, Length: 1000, dtype: float64

In [130]:
col[col.abs()>2]

9     -2.076741
20     2.429197
40    -2.100799
75     2.011999
82     2.082397
         ...   
957   -2.823345
958    2.187487
962   -2.020663
964    2.482552
966    2.048179
Name: 2, Length: 62, dtype: float64

In [133]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
8   -0.747877  3.475321 -1.655748 -1.198177
103 -0.134938 -3.378901  0.887730 -0.894421
142  1.976131  3.635538  0.390324 -2.465646
280  1.391659  1.272295 -0.416305 -3.842775
325  0.919856 -0.075615 -0.033443  3.075630
527 -3.250201  0.317664 -1.797084 -0.033551
530  0.127047  3.332820 -0.305701 -1.461579
863  0.541043 -3.120767 -0.150755  0.035155

In [134]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1 -1.0 -1.0 -1.0 -1.0
2 -1.0 -1.0 -1.0  1.0
3 -1.0  1.0 -1.0 -1.0
4 -1.0  1.0 -1.0 -1.0

## permutation and Random sampling

In [137]:
df = pd.DataFrame(np.arange(5*7).reshape(5,7))

In [138]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [139]:
sampler = np.random.permutation(5)

In [140]:
sampler

array([1, 0, 2, 4, 3])

In [141]:
df.take(sampler)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [142]:
df.iloc[sampler]

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [143]:
sampler = np.random.permutation(7)

In [144]:
sampler

array([0, 1, 3, 5, 4, 2, 6])

In [145]:
df.take(sampler,axis = "columns")

0   1   3   5   4   2   6
0   0   1   3   5   4   2   6
1   7   8  10  12  11   9  13
2  14  15  17  19  18  16  20
3  21  22  24  26  25  23  27
4  28  29  31  33  32  30  34

In [146]:
df.sample(n=3)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6

In [147]:
choices = pd.Series([1,2,3,4,4])

In [149]:
choices

0    1
1    2
2    3
3    4
4    4
dtype: int64

In [150]:
choices.sample(n=10,replace=True)

3    4
1    2
3    4
2    3
3    4
4    4
4    4
0    1
4    4
2    3
dtype: int64

In [151]:
## Computing Indicator/Dummy Variables

In [152]:
df = pd.DataFrame({"key":["a","b","c","a"], "data1":range(4)})

In [153]:
df

key  data1
0   a      0
1   b      1
2   c      2
3   a      3

In [154]:
pd.get_dummies(df["key"])

a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

In [155]:
dummies = pd.get_dummies(df["key"],prefix="keys")

In [158]:
df_with_dummies = df[["data1", "key"]].join(dummies)

In [159]:
df_with_dummies

data1 key  keys_a  keys_b  keys_c
0      0   a       1       0       0
1      1   b       0       1       0
2      2   c       0       0       1
3      3   a       1       0       0

In [160]:
mnames = ["id","title","genres"]

In [161]:
movies = pd.read_table("/Users/yuxichen/online eduction/python_data_analysis/pydata-book-3rd-edition/datasets/movielens/movies.dat",
                      sep = "::", header = None, names=mnames, engine = "python")

In [162]:
movies

id                               title                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
...    ...                                 ...                           ...
3878  3948             Meet the Parents (2000)                        Comedy
3879  3949          Requiem for a Dream (2000)                         Drama
3880  3950                    Tigerland (2000)                         Drama
3881  3951             Two Family House (2000)                         Drama
3882  3952               Contender, The (2000)                Drama|Thriller

[3883 rows x 3 columns]

In [163]:
movies[:10]

id                               title                        genres
0   1                    Toy Story (1995)   Animation|Children's|Comedy
1   2                      Jumanji (1995)  Adventure|Children's|Fantasy
2   3             Grumpier Old Men (1995)                Comedy|Romance
3   4            Waiting to Exhale (1995)                  Comedy|Drama
4   5  Father of the Bride Part II (1995)                        Comedy
5   6                         Heat (1995)         Action|Crime|Thriller
6   7                      Sabrina (1995)                Comedy|Romance
7   8                 Tom and Huck (1995)          Adventure|Children's
8   9                 Sudden Death (1995)                        Action
9  10                    GoldenEye (1995)     Action|Adventure|Thriller

In [164]:
dummies = movies["genres"].str.get_dummies("|")

In [165]:
dummies.iloc[:10,:6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [166]:
np.random.seed(12345)

In [169]:
values = np.random.uniform(size=10)

In [170]:
values

array([0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371,
       0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535])

In [171]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [173]:
pd.cut(values,bins)

[(0.6, 0.8], (0.8, 1.0], (0.0, 0.2], (0.0, 0.2], (0.2, 0.4], (0.6, 0.8], (0.8, 1.0], (0.8, 1.0], (0.8, 1.0], (0.6, 0.8]]
Categories (5, interval[float64, right]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [174]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           0           0           0           0           1
2           1           0           0           0           0
3           1           0           0           0           0
4           0           1           0           0           0
5           0           0           0           1           0
6           0           0           0           0           1
7           0           0           0           0           1
8           0           0           0           0           1
9           0           0           0           1           0

# 7.3 Extension Data Types

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
s = pd.Series([1,2,3,None])

In [5]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [6]:
s.dtype

dtype('float64')

In [8]:
s = pd.Series([1,2,3,None], dtype = pd.Int64Dtype())

In [9]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [10]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [11]:
s.dtype

Int64Dtype()

In [14]:
df = pd.DataFrame({"A": [1,2, None,4],
                  "B": ["one","two","three",None],
                  "C": [False, None, False, True]})

In [15]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [16]:
df["A"].dtype

dtype('float64')

In [17]:
df["A"].astype("Int64")

0       1
1       2
2    <NA>
3       4
Name: A, dtype: Int64

In [18]:
df["A"] = df["A"].astype("Int64")

# 7.4 String Manipulation

## Python Built-in Object Methods:

In [23]:
val = "a,b,guido"

In [24]:
val.split(",")

['a', 'b', 'guido']

In [25]:
pieces = [x.strip() for x in val.split(",")]

In [26]:
pieces

['a', 'b', 'guido']

In [27]:
first, second, third = pieces

In [28]:
"::".join(pieces)

'a::b::guido'

## regular expression

## String Functions in pandas

# 7.5 Categorical Data

In [35]:
values = pd.Series(["apple","orange","apple"]*2)

In [36]:
values

0     apple
1    orange
2     apple
3     apple
4    orange
5     apple
dtype: object

In [37]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [38]:
pd.value_counts(values)

apple     4
orange    2
dtype: int64

In [39]:
values = pd.Series([0,1,0,0]*2)

In [40]:
dim = pd.Series(['apple','orange'])

In [41]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [42]:
dim

0     apple
1    orange
dtype: object

In [43]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

## Categorical Extension Type in pandas

In [46]:
fruits = ["apple", "orange", "apple", "apple"] * 2

In [47]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [48]:
N = len(fruits)

In [49]:
N

8

In [51]:
rng = np.random.default_rng(seed = 12345)

In [54]:
df = pd.DataFrame({"fruit": fruits,
                   "basket_id":np.arange(N),
                   "count": rng.integers(3,15,size=N),
                   "weight": rng.uniform(0,4,size=N)},
                    columns = ["basket_id","fruit","count","weight"])

In [55]:
df

basket_id   fruit  count    weight
0          0   apple     14  2.691024
1          1  orange      7  3.767211
2          2   apple     13  0.992983
3          3   apple      6  3.795525
4          4   apple      9  2.668950
5          5  orange     10  0.383592
6          6   apple      5  1.767359
7          7   apple      5  3.545920

In [56]:
fruit_cat = df["fruit"].astype("category")

In [57]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [58]:
c = fruit_cat.array

In [59]:
c

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, object): ['apple', 'orange']

In [60]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [61]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [62]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [65]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [64]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [66]:
df["fruit"] = df["fruit"].astype("category")

In [67]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [79]:
cat = pd.Categorical(["foo","bar","baz"])

In [80]:
cat

['foo', 'bar', 'baz']
Categories (3, object): ['bar', 'baz', 'foo']

In [81]:
codes = [0,1,2,2,2,2]

In [82]:
cat2 = pd.Categorical.from_codes(codes,cat)

In [83]:
cat2

['bar', 'baz', 'foo', 'foo', 'foo', 'foo']
Categories (3, object): ['bar', 'baz', 'foo']

## Computations with Categoricals

In [88]:
rng = np.random.default_rng(seed=12345)

In [89]:
draws = rng.standard_normal(1000)

In [90]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [91]:
bins = pd.qcut(draws,4)

In [92]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [94]:
bins = pd.qcut(draws, 4, labels=["Q1","Q2","Q3","Q4"])

In [95]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [97]:
bins.codes[0:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [98]:
bins = pd.Series(bins, name="quartile")

In [101]:
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count', 'min', 'max'])
           .reset_index())

In [102]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

## Categorical Methods

In [107]:
s = pd.Series(['a','b','c','d'] * 2)

In [108]:
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [109]:
cat_s = s.astype("category")

In [110]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [111]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [112]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [113]:
actual_categories = ["a","b","c","d","e"]

In [114]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [115]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [116]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [117]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]

In [118]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [119]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [120]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [121]:
pd.get_dummies(cat_s3)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
4  1  0  0  0
5  0  1  0  0